### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dapeng2018** [WojciechMula/pyahocorasick#116]
Version: 1.4
Python 2.7.15

class TEST():

    def __init__(self, input_filename):
        self.ac = ahocorasick.Automaton()
        n_word = 0
        with open(input_filename) as f:
            for text in f:
                n_word += 1
                word = text.strip()
                self.ac.add_word(word, (n_word, word))
        self.ac.make_automaton()

    def test_sent(self, text):
        lines = text.strip().split('\t')
        sent = lines[0]
        res_relevant = []
        for item in self.ac.iter(sent):
            res_relevant.append(item[1][1])
if __name__ == '__main__':
    t = TEST(sys.argv[1])
    before = t.get_memory_usage()
    n_lines = 0
    with open(sys.argv[2]) as f:
        for text in f:
            n_lines += 1
            t.test_sent(text.strip())
          

The input data is very large, and memory keeps growing.

**Comment by pombredanne** [comment]
@dapeng2018 do you still use Python 2? or did you switch to Python 3?
Do you have the issue there too with 1.4.2?

**Comment by pombredanne** [comment]
@dapeng2018 I am closing for now, for lack of activity
