### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by WojciechMula** [WojciechMula/pyahocorasick#119]
The official support for Python 2 ends this year. It doesn't mean that we will drop Py2. As long as Py2 is available in Debian (which I use) any features/fixes will be available for both versions Py3 and Py2.

**Comment by pombredanne** [comment]
@WojciechMula great, that's your call though... If you consider branching for maintenance the current code and only support Python 3 for any new developments that's fine by me.

**Comment by asmithatlassian** [comment]
many of my clients cannot easily upgrade software on their servers and wind up stuck with Python2. That's why I'm searching for efficient solutions that work in both 2 and 3. Thanks for your contribution to the community!

**Comment by WojciechMula** [comment]
@asmithatlassian Thank you for your kind words.

**Comment by pombredanne** [comment]
@asmithatlassian It is hard to keep support for Python 2 as getting a way to test and build in the hosted CI's becomes harder and harder. I would be included to remove support as it is really to support something that cannot be reliably tested.  What do you think?

**Comment by WojciechMula** [comment]
There was an attempt to split the module into py2 and py3 lines. But that approach failed, as the code was duplicated and there was a lot of burdens with this.

Despite problems with testing, I think we should keep the py2 suppport. Likely we declare at some point in time, that we cannot test the py2 variant and people would use never versions on their own risk. Like in Debian, we have stable and unstable variant. Does it sound fine?

**Comment by pombredanne** [comment]
> test the py2 variant and people would use never versions on their own risk. Like in Debian, we have stable and unstable variant. > Does it sound fine?

This makes sense. Let's call 1.4.4 the latest stable supporting Python2... and branch it out for possible support.
This way you can start a clean 2.0.0 with exclusive Python 3.6+ (or may be even 3.8+) support

**Comment by pombredanne** [comment]
I am closing this as we stopped testing on Python 2 a long while ago. The upcoming v2.0 will be Python 3.7+ only
