### ISSUE TITLE
Run tests on newer Python 3 versions too

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#120]
The Travis and Appveyor Cis test suites are not running on the most recent versions of Python3. It would be useful to ensure things build and work nicely also on the latest 3.7, 3.8, etc.

**Comment by WojciechMula** [comment]
That's a good point, thanks.

**Comment by NicoMaillet** [comment]
Add also 3.9 please :)

**Comment by WojciechMula** [comment]
Sure. FYI, the latest release was tested entirely on Python 3.9. :)

**Comment by pombredanne** [comment]
I have also added Python 3.10 in the new CI for 1.4.3 ... closing now.
