### ISSUE TITLE
C interface of this repo

### ISSUE THREAD

**Issue by EricDracula** [WojciechMula/pyahocorasick#121]
I am searching the Github for a good C implementation of the Aho-Corasick algorithm, but currently no one is suitable. I have used pyahocorasick in my python program before, and I am familiar with its interfaces. Since pyahocorasick is realized on the basis of cython, so I wonder whether it is possible for this repo to expose C interface as well...

**Comment by WojciechMula** [comment]
Hi, I was thinking about that, but the current implementation is too coupled with Python C API. I would rather rewrote everything in C++ and then expose Python and C interfaces.

**Comment by EricDracula** [comment]
> Hi, I was thinking about that, but the current implementation is too coupled with Python C API. I would rather rewrote everything in C++ and then expose Python and C interfaces.

Wow, that is really cool. I am looking forward to it. Thanks.

**Comment by mingzian** [comment]
Just wanted to double check if there are there any plans for a C or C++ API? The best implementation of the algo I know is pyahocorasick, so it would be really great to have it available in C or C++ as well!

**Comment by WojciechMula** [comment]
I considering only C++ (and then some C wrapper), as C++ template would easily let to experiment with different memory layouts, allocators, data types etc. As a side effect, it would allow having a more robust Python solution.
