### ISSUE TITLE
Support to select longest available match without overlap

### ISSUE THREAD

**Issue by giriannamalai** [WojciechMula/pyahocorasick#127]
We need support for longest match without overlapping.

Ex:
Keyword 1: python
Keyword 2: Python programming

After running iteration over the following sentence:
I love python programming.

Result should be **"Python programming"**. 
Not both **"Python and Python Programming"**

**Comment by pombredanne** [comment]
This is a feature in the latest 1.4.2 ... See https://pyahocorasick.readthedocs.io/en/latest/#iter-long-string-start-end
Thanks!
