### ISSUE TITLE
Error installing pyahocorasick through pip and setup.py

### ISSUE THREAD

**Issue by KennSmithDS** [WojciechMula/pyahocorasick#129]
I am getting this error when I run "pip install pyahocorasick"

ERROR: Failed building wheel for pyahocorasick
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

I am getting this error when I clone the repo and run "python setup.py install" from the repo directory:

error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

This is my coding environment:
- Windows 10
- Python 3.7.7
- Conda 4.8.3 (miniconda)
- Visual Studio 2019 (w/ latest build tools - does this not include 2014?)

![py37_pyahocorasick_pip_install_issue](https://user-images.githubusercontent.com/30271891/81511063-7d836180-92cb-11ea-8255-25ad6511b75a.PNG)
![py37_pyahocorasick_setuppy_install_issue](https://user-images.githubusercontent.com/30271891/81511064-7d836180-92cb-11ea-9f1c-3caa1c98e526.PNG)

**Comment by zahraazin** [comment]
@KennSmithDS Could you fix this? I have the same problem.

**Comment by Dobatymo** [comment]
It builds perfectly with Visual Studio 2017. I haven't any other installed to test.

**Comment by NeilWP** [comment]
I am using Visual code  not stdio and I followed the initial  help instructions and installed the latest build tools from Microsoft. I get the error 
ERROR: Command errored out with exit status 1: 

'C:\Users\oejwp\Documents\PythonDev\Crypto\env_Crypto\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\oejwp\\AppData\\Local\\Temp\\pip-install-8j_e6fxg\\pyahocorasick_313d39c66f264b35a203e476ac580983\\setup.py'"'"'; __file__='"'"'C:\\Users\\oejwp\\AppData\\Local\\Temp\\pip-install-8j_e6fxg\\pyahocorasick_313d39c66f264b35a203e476ac580983\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\oejwp\AppData\Local\Temp\pip-record-kwbsyq0k\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\oejwp\Documents\PythonDev\Crypto\env_Crypto\include\site\python3.9\pyahocorasick' Check the logs for full command output.

**Comment by pombredanne** [comment]
I am preparing a new release and will push wheels for all OSes.

**Comment by pombredanne** [comment]
Closing now. https://github.com/WojciechMula/pyahocorasick/actions has wheels built on each commit... and 1.4.3 will have these published on PyPI for windows/macos/linux.
Thank you all!

**Comment by NeilWP** [comment]
look forward to this. 
Many thanks

Neil
