### ISSUE TITLE
save/load silently discards tuple data

### ISSUE THREAD

**Issue by pquentin** [WojciechMula/pyahocorasick#130]
## How to reproduce

Run the following script:

```
import pickle
import ahocorasick

A = ahocorasick.Automaton(ahocorasick.STORE_ANY)
A.add_word("word", (1, 2))
A.make_automaton()
print(list(A.iter_long("find word")))

A.save("/tmp/a", pickle.dumps)
B = ahocorasick.load("/tmp/a", pickle.loads)
print(list(B.iter_long("find word")))
```

## Expected result

The documentation says that save/load is supported with `STORE_ANY`, so I would expect to see the same list twice:

```
[(8, (1, 2))]
[(8, (1, 2))]
```

An exception would be fine too.

## Actual result

The tuple is silently cropped:

```
[(8, (1, 2))]
[(8, 1)]
```

**Comment by zhu** [comment]
The tuple is not cropped, but unpacked.
It will raise exception when the tuple has more elements or the second element is larger than 5 or not a number.

see https://bugs.python.org/issue28977

> PyObject_CallFunction(func, "O", arg) calls func(arg), or func(*arg) if arg is a tuple

https://github.com/WojciechMula/pyahocorasick/blob/90b3079d1465b49849b128f697bbbaefc57e5122/src/custompickle/save/automaton_save.c#L108

maybe change to `PyObject_CallFunctionObjArgs(func, arg, NULL)` will solve this issue.

**Comment by WojciechMula** [comment]
Thank you very much @zhu for the fix. It's highly appreciate.

I have just released 1.4.2. @pquentin, please check if this solves your problem.

**Comment by WojciechMula** [comment]
Reopening. I misclicked. :) Sorry.

**Comment by pquentin** [comment]
I won't be able to test this soon as I no longer use this library for different reasons If @zhu fixed it, then it's fixed! Closing, thanks everyone
