### ISSUE TITLE
Either drop Travis or switch to Travis.com

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#140]
Travis support for FOSS projects has changed. It now can take forever to complete a build. The possibilities are:
- switch to something else (e.g. Azure, GitHub actions, Circle CI, GitLab, etc.)
- try Travis.com
 
 
I have a decent build loop for Azure here https://github.com/nexB/scancode-toolkit/blob/develop/azure-pipelines.yml that tests on multiple Linuxes, Windowses and macOSes on Python 3.6 to 3.9... we could adopt and adapt this for here easily

**Comment by WojciechMula** [comment]
Thanks for info about Travis.com, I was considering switching to it. Seems it's not worth.

I'm completely unfamiliar with these open source CI alternatives, could you please suggest what's worth to check.

This azure solution is not free, right?

**Comment by pombredanne** [comment]
> I'm completely unfamiliar with these open source CI alternatives, could you please suggest what's worth to check.
> This azure solution is not free, right?

Azure pipelines and GitHub actions are "free as in beer" for open source projects alright.

**Comment by pombredanne** [comment]
> Thanks for info about Travis.com, I was considering switching to it. Seems it's not worth.

I feel like they have abandoned supporting open source projects.

**Comment by pombredanne** [comment]
I an setting up GitHub action(s) that are built in

**Comment by pombredanne** [comment]
We now have https://github.com/WojciechMula/pyahocorasick/actions running may OS/Python combos on each commit and also building wheels and sdist! :tada: 
We can reopen if we want to reactivate travis.
