### ISSUE TITLE
installing wheel for pyahocorasick==1.4.1 in python3.6.8

### ISSUE THREAD

**Issue by Mohit-15** [WojciechMula/pyahocorasick#143]
Hello,
I was installing pyahocorasick version 1.4.1 using pip, but it fails to build the wheel. I don't get where this error comes from. Please help me solve this issue.

![image](https://user-images.githubusercontent.com/52665879/111894552-a3bc7680-8a31-11eb-8c2f-d4a0cfb6dde9.png)

**Comment by WojciechMula** [comment]
You are missing MSVC installation on your computer. The error message gives you the URL for download the compiler.

**Comment by Mohit-15** [comment]
Thank You. I'll try with this
