### ISSUE TITLE
Tag release 1.4.2 and publish pre-built wheels

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#146]
This is a todo for me:
1. the PyPI release is 1.4.2 but we do not have a tag for it
2. I need to build and publish pre-built wheels for most OSses to PyPI

**Comment by fabaff** [comment]
I would like to see the `1.4.2` tag as well.

**Comment by pombredanne** [comment]
This has been tagged correctly. I made a diff with the actual released 1.4.2 sdist and merged and tagged all this back into the master branch.
