### ISSUE TITLE
Pypi home page link is incorrect

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#15]
On https://pypi.python.org/pypi/pyahocorasick/1.0.0 the link to this Github repo is incorrect:
It is:
`Home Page: http://github.com/WojciechMula/pyhocorasick `
and it should be instead:
`https://github.com/WojciechMula/pyahocorasick`

**Comment by WojciechMula** [comment]
I've fixed the URL in the new version https://pypi.python.org/pypi/pyahocorasick/1.0.1
