### ISSUE TITLE
Add funding/sponsoring info to docs

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#153]
Some folks may be interested to sponsor @WojciechMula work on the project
Let's add a the doc and repo settings to enable this

**Comment by pombredanne** [comment]
ack.. closing.

**Comment by WojciechMula** [comment]
I'm really unhappy with this. I mean, the module is quite good, I also have some ideas about how to improve it. And our users also come with their needs. At the same time, I'm unable to work on the module.

**Comment by pombredanne** [comment]
> I'm really unhappy with this. 

You should not but I can understand the frustration if your health is playing bad tricks on you.

>I mean, the module is quite good, I also have some ideas about how to improve it. 

It is more than quite good. This is great.

> And our users also come with their needs. At the same time, I'm unable to work on the module.

No worries... take it easy!
Do you want to reopen this issue though? or should I leave it closed?
I could find some help... that was the idea with this issue in the first place and you could provide some minimal guidance.
