### ISSUE TITLE
Release 1.4.3

### ISSUE THREAD

**Issue by jonashaag** [WojciechMula/pyahocorasick#158]
Hi @WojciechMula! Thanks for this great library. Can you make a release that contains https://github.com/WojciechMula/pyahocorasick/commit/e6419b13c1ce8707adb2541f7e1f74324fb7c9d4?

**Comment by pombredanne** [comment]
@WojciechMula I can handle it if you like. I'll take care of tagging 1.4.2 along the way and setup https://github.com/pypa/cibuildwheel/ to build native wheels at once.

**Comment by pombredanne** [comment]
I worked out a branch in https://github.com/WojciechMula/pyahocorasick/pull/160 and I will push a release later today.
Closing now
Thank you ++ :heart:
