### ISSUE TITLE
Doc on wildcards.... wildcards preprocessor has no support for escape sequence, so wildcards can't match characters ? nor *

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#17]
In the example 1, https://github.com/WojciechMula/pyahocorasick/blob/7fc453f58e7187fbc5622695b466d0337c4b21f1/README.rst#example
we have `for item in A.iter("_hershe_"):` to find all occurrences...
I could not find much doc on the significance of this magic underscore... How does this relate to wildcards? Can the underscore or a wildcard also be used as a characters in indexed "words"? where is the code is this underscore processed?

**Comment by WojciechMula** [comment]
Underscores have no special meaning, I used them in the example to merely mark the borders of the searched string. The only methods where wildcards are used are methods: keys, values and iter.

Underscore and wildcards chars could be used in dictionary entries. But I'm afraid that wildcards preprocessor has no support for escape sequence, so wildcards can't match characters ? nor * -- clearly a bug.

**Comment by pombredanne** [comment]
@WojciechMula Thanks for the clarifications! ... I am not too worried about the wildcards not being matchable... though it could make sense to update the README accordingly and let me update this ticket and keep this open for reference.

**Comment by WojciechMula** [comment]
@pombredanne I've just commited updates to README. Could you please verify if it is OK?

**Comment by pombredanne** [comment]
@WojciechMula Just did. Looks good

**Comment by WojciechMula** [comment]
@pombredanne Thank you
