### ISSUE TITLE
PUBLISH BINARY WHEELS PLEASE

### ISSUE THREAD

**Issue by HarryCaveMan** [WojciechMula/pyahocorasick#180]
NO EXPLANATION NEEDED. C modules that are compiled to native should not require compilation (and, by extension,  gcc, and python.h) every time they are installed. This is especially true now that wheel has support for both glibc and musl. hy whold thousands (maybe more) of users be required to install an entire compiler toolkit and python-devel headers just because y'all don't want to publish 2 binary wheels.

**Comment by Dobatymo** [comment]
1. I don't know what you are complaining about, there are wheel files for many different platforms here https://pypi.org/project/pyahocorasick/#files
2. Even if there would not be any, there is no reason to simply demand them without any contributions from your side. Or maybe simply don't shout.

**Comment by pombredanne** [comment]
@Dobatymo @HarryCaveMan working on pushing one today!

**Comment by pombredanne** [comment]
(that's going to be for a final v2.) ...as @Dobatymo there is a sizeable set of wheels published ;)
@HarryCaveMan which os/arch do you use?

**Comment by pombredanne** [comment]
The new release is on its way, but in all cases we are publishing the wheels alright, so I am closing this.
