### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by FreePlague** [WojciechMula/pyahocorasick#188]
Please, someone, build Python 3.12 wheels.

**Comment by FreePlague** [comment]
@pombredanne, maybe you can help.

**Comment by pombredanne** [comment]
Yes! the build is all automated in https://github.com/WojciechMula/pyahocorasick/blob/master/.github/workflows/test-and-build.yml so adding 3.12 should a simple thing. Beyond this we could also add ARM builds

**Comment by pombredanne** [comment]
This has been merged. Release coming up soon.

**Comment by FreePlague** [comment]
Awesome!
