### ISSUE TITLE
Python 3.4.3 segmentation fault on ahocorasick.clear()

### ISSUE THREAD

**Issue by pvphaneuf** [WojciechMula/pyahocorasick#19]
The following code is causing a segmentation fault with Python 3.4.3. The segmentation fault manifests after the call to clear().

```
import ahocorasick
A = ahocorasick.Automaton()
for index, word in enumerate("he her hers she".split()):
   A.add_word(word, (index, word))
A.clear()
```

**Comment by WojciechMula** [comment]
@pvphaneuf Could you please paste the output from following script:
```
import sys
print(sys.version)
print(sys.version_info)
``` 
Python3 from debian prints:

```
3.4.4rc1 (default, Dec  7 2015, 11:09:54) 
[GCC 5.3.1 20151205]
sys.version_info(major=3, minor=4, micro=4, releaselevel='candidate', serial=1)
```
and the problem doesn't manifest in that version.

**Comment by pvphaneuf** [comment]
3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

**Comment by pvphaneuf** [comment]
Seems like I should update.

**Comment by WojciechMula** [comment]
Thanks. I've just downloaded Python 3.4.3 from python.org, but have slightly different output than yours:
```
3.4.3 (default, Apr 23 2016, 06:45:54) 
[GCC 4.9.2]
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
```
And in this particular version no segfault occurs. Do you use Linux? which distro?

**Comment by pvphaneuf** [comment]
Ubuntu 14.04.3 LTS

**Comment by WojciechMula** [comment]
@pvphaneuf Thanks. I'm not familiar with Ubuntu versions, and the only python3.4.3 I was able to locate is here http://packages.ubuntu.com/wily/python3.4. Is it correct version?

(I've downloaded sources from that url, extracted original sources, applied patches from debian/patches subdirectory and built the program. No errors reported.)

**Comment by pvphaneuf** [comment]
Seems like it therefore might be contention versus my system setup.

I won't be able to do any major updates any time soon on the system manifesting this issue since it's a production server for a web platform.

In the next update cycle for the production server, I'll try to remember to test this out again and get back to you.

**Comment by WojciechMula** [comment]
Could you get actual Python sources from your machine (using apt-get source), and somehow share them with me?

**Comment by pombredanne** [comment]
@pvphaneuf Is this bug still current? if so could you provide some update? otherwise do you mind closing it?

**Comment by pvphaneuf** [comment]
Currently not able to pursue further testing on bug.
