### ISSUE TITLE
Need an iter_long() method [was: Question about functionality. ]

### ISSUE THREAD

**Issue by Ulitochka** [WojciechMula/pyahocorasick#21]
Hello, and thanks for your work.
1. It's possible to save a trie. Something like pickle format?
2. Module ahocorasick by Danny Yoo has this method: search_long(query, [startpos]). Same as search(), except that this searches for the longest leftmost keyword that matches. pyahocorasick has smth like this method?

**Comment by WojciechMula** [comment]
Ad 1. Yes. In fact Aho-Corasick automaton is a trie plus some extra inter-node links, so the trie must be saved. But unfortunately pickling in 64-bit doesn't work - see #20.
Ad 2. I have no idea how such function should work. Could you please provide an example, I mean an input and the expected output.

**Comment by Ulitochka** [comment]
import ahocorasick
tree = ahocorasick.KeywordTree()
tree.add("alpha")          
tree.add("alpha beta")
tree.add("gamma")

tree.make()

tree.search("I went to alpha beta the other day to pick up some spam")
(10, 15)

tree.search_long("I went to alpha beta the other day to pick up some spam")
(10, 20)

**Comment by WojciechMula** [comment]
@Ulitochka Thanks a lot! I have to understand it now.

**Comment by WojciechMula** [comment]
@Ulitochka Could you please clarify?

Let say a trie contains 4 words:
* alpha
* alpha beta
* beta gamma
* gamma

And we match a string "Cats have not idea what alpha beta gamma means". The method should match strings:
1. "alpha beta" and "gamma" or
2. "alpha beta" and "beta gamma"?

In other words is overlapping allowed or not?

**Comment by Ulitochka** [comment]
Thanks for your question.
I think we use this rule: the longest leftmost keyword. In this case -> 1. "alpha beta" and "gamma". Without overlapping.

**Comment by WojciechMula** [comment]
Thanks a lot. Now I know how to write it. :)

**Comment by Ulitochka** [comment]
Thank you for your greate work!

**Comment by WojciechMula** [comment]
@Ulitochka I've just added python implementation. Could you please check it, or post some additional test cases?

If everything is OK, I'll translate it in C.

**Comment by Ulitochka** [comment]
Ok. i will check it.

**Comment by WojciechMula** [comment]
@Ulitochka In the meantime I translated code to C, see https://github.com/WojciechMula/pyahocorasick/commit/c5ff16460a8bbe895231340a8585566dd516233a

**Comment by pombredanne** [comment]
@Ulitochka Any feedback? Is this working OK for you?

**Comment by pombredanne** [comment]
@Ulitochka : ping? any feednack?

**Comment by dsachs** [comment]
Hi, this method (`iter_long`) would be useful for me, but I'm not sure how to test it--and I'm entirely unfamiliar with C development, I'm afraid. (I'm on MacOS, fwiw.)

Should I just check out the branch `iter_long-rebased` in a virtualenv and `python setup.py install`? Or is it pretty out of date at this point?

Thanks for the great work!
-David

**Comment by pombredanne** [comment]
@dsachs that would be the gist of it.
You want to make sure you do this in a virtualenv ... not in a global install.
On Mac, this likely need you to have some Xcode installed for compiling C.

**Comment by dsachs** [comment]
Just tried it in a virtualenv (using Python3 as the interpreter). I got a series of warnings (probably irrelevant) and errors, listed below. Sorry I can't be more helpful, I'm afraid I'm just a Java/Python guy.

Console log attached.

[error_log.txt](https://github.com/WojciechMula/pyahocorasick/files/1237022/error_log.txt)

**Comment by pombredanne** [comment]
@dsachs This is not entirely surprising since this branch fails also on travis https://travis-ci.org/WojciechMula/pyahocorasick/jobs/190971147

Now did you try the pure Python version in https://github.com/WojciechMula/pyahocorasick/commit/12c4b93e590d6913e318ce96d6cc1db2bb7830b6 ?

I personally think that working or not this is feature that is not yet entirely specified IMHO

**Comment by Salma7amed** [comment]
This functionality 'iter_long' was not merged due to lack of response. I believe it is extremely useful, would it be possible to reconsider merging it?

**Comment by pombredanne** [comment]
@Salma7amed would you be willing to take a shot at reviving the branches?

**Comment by Salma7amed** [comment]
@pombredanne I was going to go for that solution if it is decided to leave it as it is. It's just I thought since I can see a couple of people beside me are asking for it too, then why not have it accessible to everyone by default.

**Comment by pombredanne** [comment]
@Salma7amed Could you try the code in the branch and report if this works for you as it is for now?

**Comment by Salma7amed** [comment]
@pombredanne I rebased iter_long to master branch, resolved a few conflicts, installed the package in my virtual environment and did a quick test. And it seems to be working fine. 
Is this enough, or do you need me to do intensive testing as well as run the unit test?

**Comment by pombredanne** [comment]
@Salma7amed that's more than enough for a start! thank you ++ for that :bowing_man: 
If you do not mind to test a bit more that would be much welcomed. Also if you could push your rebase in a branch and submit a PR that would be absolutely lovely.

**Comment by WojciechMula** [comment]
@Salma7amed Thank you for picking it up. If you could test that code it'd be great.

**Comment by Salma7amed** [comment]
@WojciechMula @pombredanne Ok, I will further test it and get back to you with a pull request later this week.

**Comment by Salma7amed** [comment]
@WojciechMula @pombredanne I did some testing and double-checked if all the unit-tests succeded, everything looks fine.

**Comment by WojciechMula** [comment]
The Salma's branch was merged. Thank you very much for your effort! I should have merged this years ago... it was ready.

I have already done minor fixes, but need more testing of this feature before official release. That's a call for more unit tests, fixes and enhancements. :)

**Comment by Salma7amed** [comment]
@WojciechMula are you planning on releasing a new version?

**Comment by WojciechMula** [comment]
@Salma7amed once I fully test it, have done it yet

**Comment by pquentin** [comment]
As someone migrating away from a custom fork of https://github.com/JDonner/NoAho I'd like to use `iter_long` as soon as it is released. It looks like the Windows build failures need to be resolved before releasing?

**Comment by pombredanne** [comment]
This has been released last year in version 1.4.2. Closing now... there is an upcoming 1.4.3 release anytime too
