### ISSUE TITLE
calling get before first add_word crashes

### ISSUE THREAD

**Issue by Snucker** [WojciechMula/pyahocorasick#22]
There is no root in the trie until add_word is called therefore  trienode_get_next fails its assert.

```
import ahocorasick
a = ahocorasick.Automaton()
a.get('foo', None)
```
results in

`trienode.c:trienode_get_next:33 - node failed!`

**Comment by Snucker** [comment]
Ahh sorry I seem to be running an older version.

**Comment by WojciechMula** [comment]
It is a good test case for unit tests. :)

**Comment by WojciechMula** [comment]
@Snucker  It's a bug, unfortunately.
