### ISSUE TITLE
Links to projects using pyahocorasick

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#34]
This could be either in the README or best in a wiki page. This could make sense as a new release is coming up to provide some pointers as example of real world usage.

I collected these few links to projects that use pyahocorasick:

 * @ErikGartner https://github.com/ErikGartner/sentimental
 * @urdvr @paultammo @estnltk https://github.com/estnltk/episode-miner
 * @dmitryfisko https://github.com/dmitryfisko/search
 * @mbonakda @hopper-project https://github.com/hopper-project/hopper-tools
 * @pombredanne @nexB https://github.com/nexB/scancode-toolkit

**Comment by WojciechMula** [comment]
Great idea! A wiki page seems to be better place for this.

**Comment by pombredanne** [comment]
I created a wiki page: https://github.com/WojciechMula/pyahocorasick/wiki/FAQ

**Comment by WojciechMula** [comment]
Thanks @pombredanne, looks really good. I had no idea, that so many people use the module. :)
