### ISSUE TITLE
Generate and publish API doc

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#35]
... rather than maintaining that in the README

**Comment by WojciechMula** [comment]
Are there any tools we can use?

**Comment by pombredanne** [comment]
Yes, sphinx https://pypi.python.org/pypi/Sphinx/1.4.5

**Comment by pombredanne** [comment]
And then pushing the doc as part of the build to https://readthedocs.org/

**Comment by WojciechMula** [comment]
Sound great! Have you any experience with sphinx?

**Comment by WojciechMula** [comment]
I know ReSt and use it for my webstite, but I've never used sphinx.

**Comment by pombredanne** [comment]
I do. It is just a generator for ReST

**Comment by pombredanne** [comment]
I will commit something. You will need to register on readthedocs.org. the simplest would be to hook all this in the travis build.

**Comment by pombredanne** [comment]
@WojciechMula see #36 for your review

**Comment by pombredanne** [comment]
And to get this pushed to readthedocs.org 
1. create an account 
2. setup a webhook here as explained there: http://read-the-docs.readthedocs.io/en/latest/webhooks.html

**Comment by pombredanne** [comment]
@WojciechMula Time for a release now ? :+1:

**Comment by WojciechMula** [comment]
OK, the docs were published: http://pyahocorasick.readthedocs.io/en/latest/ Documentation looks really nice now. Thank you.

And it's time to release. :)

**Comment by pombredanne** [comment]
@WojciechMula Thank you my Lord!

**Comment by WojciechMula** [comment]
@pombredanne LOL :)

**Comment by pombredanne** [comment]
I just pushed a minor update to the README linking to the doc . Direct into master ;)

**Comment by WojciechMula** [comment]
Great, so now I'm tagging the repo.

**Comment by WojciechMula** [comment]
@pombredanne Done.
