### ISSUE TITLE
Display of README on Pypi

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#38]
See https://pypi.python.org/pypi/pyahocorasick/1.1.1
This is not looking good.
There are some limits to what ReST features Pypi supports.
The issue is likely around links: 
- http://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org
- http://inre.dundeemt.com/2014-05-04/pypi-vs-readme-rst-a-tale-of-frustration-and-unnecessary-binding/

**Comment by pombredanne** [comment]
This may help https://mg.pov.lt/restview/

**Comment by pombredanne** [comment]
Note that I played a bit with this this week-end trying to find where in the README ReST there is something that makes Pypi choke. There is something for sure and restview pointed to errors though I could not tell which one exactly...

**Comment by WojciechMula** [comment]
@pombredanne Maybe we could we use shorter README for PyPI? Just an introduction and the link to readthedocs.org.

**Comment by pombredanne** [comment]
> Maybe we could we use shorter README for PyPI? Just an introduction and the link to readthedocs.org.

Definitely. This is redundant now. Let me streamline this and send a PR

**Comment by WojciechMula** [comment]
Thanks a lot! Your contribution in docs in priceless.

Is it possible to an update existing version of package on PyPI? Or we have to make a new release?

**Comment by pombredanne** [comment]
The simplest is to publish a new dot version. And this make sense since the code was updated too.

**Comment by pombredanne** [comment]
You wrote:
> Thanks a lot! Your contribution in docs in priceless.

Thank you for your appreciation! it's not like I am putting lipstick on a bullddog: your code is great. Some decent doc is what will make it known.

I am also a selfish bastard: since I am using this library seriously now, I want it to be successful and healthy: with a good looking and decent doc, the likeliness some other folks will use it increases and more users may contribute to its well being ;)

**Comment by WojciechMula** [comment]
Hmm, still doesn't look good. Maybe we should remove from setup.py option long_description? The homepage of package is displayed on PyPI, for a potential user checking out the docs would cost one additional click.

**Comment by WojciechMula** [comment]
@pombredanne Thank you for kind word about the code. :) And you're perfectly right, a documentation is the ad of module. It should be nice and clean.

I wish I could spend more time on this project (and other side projects), but shortage of time is terrible. Moreover, my doctors say that I must not spend whole day at front of computer. :)

**Comment by pombredanne** [comment]
> Maybe we should remove from setup.py option long_description

Let me craft a simple long description just for Pypi.

**Comment by pombredanne** [comment]
@WojciechMula this is because the setup.py tries to truncate the readme. I made some changes and tested them here by updating manually the long description on Pypi: https://pypi.python.org/pypi/pyahocorasick/1.1.2

If you have no objections, I can push a new release to Pypi. For now I made these changes in the aptly number #42 PR.

**Comment by WojciechMula** [comment]
Now looks OK, great! Of course, please upgrade PyPI.

**Comment by pombredanne** [comment]
I tagged 1.1.3 and pushed a new Pypi release with `python setup.py clean --all sdist --formats=bztar,gztar,zip register upload`
It is there: https://pypi.python.org/pypi/pyahocorasick/1.1.3

**Comment by pombredanne** [comment]
I ended up repushing a new 1.1.5 release because of the bad URL fixed https://github.com/WojciechMula/pyahocorasick/commit/2144668e44e0b5a72c7c4fa2337df171667b3eeb
