### ISSUE TITLE
Setup CI on Windows

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyahocorasick#39]
Appveyor works well for this. 
You can see a super simple setup here as an example: https://github.com/nexB/scancode-toolkit/blob/develop/appveyor.yml

**Comment by WojciechMula** [comment]
Is it a free service, like travis?

**Comment by pombredanne** [comment]
@WojciechMula yes, this is like Travis but for Windows. On a side note you should ask Travis to enable MacOSX support too, this way you could test both Linux and Mac on Travis and Windows on Appveyor.
This is what I do on scancode FWIW.

**Comment by WojciechMula** [comment]
Thanks. I just skimmed through documentation and TBH I didn't get how to specify a bulding method/compiler. Could you please help me with this?

**Comment by pombredanne** [comment]
I would look at https://github.com/ogrisel/python-appveyor-demo @ogrisel stuff is always serious!

**Comment by pombredanne** [comment]
Check also: https://packaging.python.org/appveyor/ and 
https://www.appveyor.com/docs/installed-software

**Comment by WojciechMula** [comment]
Thank you very much. The pages look pretty nice, I hope I'll be able to move forward now. :)

**Comment by pombredanne** [comment]
@WojciechMula Unless you made some progress there beside https://github.com/WojciechMula/pyahocorasick/commit/8094595bc559d95f7992df8c70082db5f9e0b108 I can take on this one alright: I need to build a Windows wheel for scancode anyway.

**Comment by WojciechMula** [comment]
If you can, please do. I haven't got time even to read the docs you've linked.

**Comment by pombreda** [comment]
It's mine then!

**Comment by pombredanne** [comment]
We now have minimal litfoff: https://ci.appveyor.com/project/WojciechMula/pyahocorasick/
Next will be to ensure that:
 - we build on Python 3
 - tests are effectively being run (we are missing a make on Windows, so tests need to be refactored in a conventional Python layout)
 - built wheels are eventually uploaded in some place so they could be fetched and uploaded to Pypi at release time

**Comment by WojciechMula** [comment]
Great! Now I see how easy it was. :)

**Comment by pombredanne** [comment]
I made some experiments to build the mac, and windows wheels here: https://github.com/pombreda/thirdparty and manylinux build here: https://github.com/pombreda/thirdparty-manulinux
This uploads the wheels there http://dl.bintray.com/pombreda/thirdparty/
and we could have the same setup here and then fetch the built wheels from a bintray or similar account then upload them to Pypi for a release.

**Comment by WojciechMula** [comment]
I haven't got experience with the tools you mentioned. Should I setup dedicated account on bintray? Could we somehow automate releases? I mean one command to build wheels, upload package to pypi, upload them to pypi,  and so on.

**Comment by pombredanne** [comment]
@WojciechMula welcome back! Let me push a branch and we can then take it from there.
I will add a script to handle it all and you will just have some instructions left as a todo hopefully

**Comment by WojciechMula** [comment]
@pombredanne Great! :)

**Comment by WojciechMula** [comment]
@pombredanne We have appveyor working well, but what about this pypi integration?

**Comment by WojciechMula** [comment]
@pombredanne It seems this project doesn't need any release automation that you proposed; we have a few releases last year, which is perfectly handled manually. :)
