### ISSUE TITLE
Word segmentation on strings without spaces

### ISSUE THREAD

**Issue by ChristosChristofidis** [WojciechMula/pyahocorasick#44]
Could aho corasick (this module in particular) be used for such task ?  I am asking as I have not previously used said algorithm  and I didn't find an example showcasing this use.

For Example:

"hellotherehowareyou" --> "hello there how are you"  Now with dynamic programing you could do this in O(N^2) . . .  can we do better ? aho corasick seems like the way to go?

**Comment by WojciechMula** [comment]
The Aho-Corasick algorithm allows you to find all occurrences of words from a list. So I think it may help in your problem.

However, I'm pretty sure it won't solve problem of ambiguous strings. What about: "thereare..." -> "there are..."/"the rear e..."?

You will get positions of all words from your list, but later you need to select one of many valid options. Although locating words is done in linear time, I guess the whole algorithm will have worse complexity.

**Comment by ChristosChristofidis** [comment]
Thank you for your answer.

The ambiguity will not be a major problem in my case . Can it also match substrings instead of just prefixes? Say I search for 'hi' in a list of strings. Can I get back the word "this" ? Right now If I search 'hi' I will get something like "hi","hill" ,"hip","hixxx" ect

**Comment by WojciechMula** [comment]
Automaton searches for all words you add to it, in order to recognize "this" and "matching" you must add these words. Here is a sample program:

```
import ahocorasick

# build automaton
A = ahocorasick.Automaton()
for index, word in enumerate('hi this matching ching'.split()):
    A.add_word(word, (index, word))

A.make_automaton()

# search words
for item in A.iter('this matching'):
    print(item)
```

It prints:

```
(2, (0, 'hi'))
(3, (1, 'this'))
(10, (0, 'hi'))
(12, (2, 'matching'))
(12, (3, 'ching'))
```

As you see all words were found, even overlapped.

**Comment by matanster** [comment]
On the same aspect, any built-in option to _avoid_ matching search words appearing as sub-words?

**Comment by WojciechMula** [comment]
@matanster There's no such option. AFAIK automaton is not able to distinguish a proper word from its sub-words.
