### ISSUE TITLE
Segfault in python3

### ISSUE THREAD

**Issue by WojciechMula** [WojciechMula/pyahocorasick#5]
Simon Rosenthal has reported that following code causes segfault:

``` python
import sys
import ahocorasick
import pdb

#pdb.set_trace()
A = ahocorasick.Automaton()

# add some words to trie
for index, word in enumerate("he her hers she".split()):
    A.add_word(word, (index, word))
A.make_automaton()

# then find all occurrences in string
for item in A.iter("_hershe_"):
    print(item)
#
A = None #### segfault here
sys.exit(0)
```

**Comment by WojciechMula** [comment]
Code wasn't compatible with 64-bit architectures.
Fixed in commits ffe6e4546c0c3e306a9f90a12a2d47d3bf074c9c and b0465360fd91b9d18611858f267b86c0ef391476.

**Comment by WojciechMula** [comment]
There are still some problems related to the issue, as reported by Jonathan Grs.

**Comment by pombredanne** [comment]
@WojciechMula Is this still relevant? I have not experienced any such segfaults on Linux 64.

**Comment by WojciechMula** [comment]
I have to recheck Jonathan's report, maybe the problem has gone.

**Comment by woakesd** [comment]
No error in 64 bit python 3.5.2 on Windows and no error on Python 3.4.3 in Ubuntu. Pretty sure the later is 64 bit as it is an Ubuntu server in Azure.

**Comment by WojciechMula** [comment]
@woakesd Thanks for checking this. I still have the bug report sent via e-mail and need to check it.

**Comment by WojciechMula** [comment]
I'm closing this issue. I'll dig up these e-mails and create appropriate bugs (if needed).
