### ISSUE TITLE
End position out after supplementary plane character in Windows

### ISSUE THREAD

**Issue by woakesd** [WojciechMula/pyahocorasick#53]
This is an issue with Python under windows only. The attached sample illustrates the problem.

I presume this is because Windows python builds are narrow builds (16 bits per character and supplementary plane characters are stored as a supplementary pair).

I can add the 🙈 as a word and I get a match for it, though end is 9!

[issue.txt](https://github.com/WojciechMula/pyahocorasick/files/696300/issue.txt)

**Comment by WojciechMula** [comment]
Could you please attach output from the program, on my Linux machine it prints:

```
$ ~/github/pyahocorasick$ python3 bug_53.py 
(6, 'punched') punched
(16, 'punched') punched
```

**Comment by woakesd** [comment]
I get the following:

PS C:\Projects\pyahocorasick> py -3 .\bug_53.py
(6, 'punched') punched
(17, 'punched') unched?

I'm pretty sure this is because in windows the string passed in is two byte characters, and the higher plane characters are sent as complementary pairs (two two byte characters).

**Comment by WojciechMula** [comment]
@woakesd I will check it tomorrow, when download MSVC build toolchain. I have just MSVC 2008, Py3k needs the newest one.

**Comment by woakesd** [comment]
You can use VS2015 community edition. 

Good luck. 

📞 0131 332 7571
📱 07966 444 615
📧 david@woak.es
💻 www.woakes.net

**Comment by WojciechMula** [comment]
@woakesd OK, I've just reproduced the error, now need to work out a solution.

**Comment by WojciechMula** [comment]
@woakesd I pushed the fix to the master. Could you please check it?

**Comment by woakesd** [comment]
Tested this and the simple test passes, which is good.

But on a larger test with 50000 strings in the Automaton I get ValueError exceptions thrown randomly when searching a series of messages. I'm repeating the test and it fails on a different message each time.

Example:

Malformed UCS-2 string: expected a high surrogate at 1662, got dd00 (the position and code change on each run).

I'm struggling to produce a simple test which demonstrates this though. Grr.

Initially I was suspicious of my data but after running it repeatedly it fails in different places.

**Comment by woakesd** [comment]
I don't really want to post my test data here, can I send them to you privately?

**Comment by WojciechMula** [comment]
Thank you very much for testing! Please send your test at wojciech_mula@poczta.onet.pl Nothing would leak, don't worry.

**Comment by woakesd** [comment]
Thank you! Will check out the changes later tonight or tomorrow perhaps. It may need to wait till Friday.

**Comment by woakesd** [comment]
This is fixed as far as I am concerned so I am closing it.

**Comment by woakesd** [comment]
I'm putting together another regression test for this as I found an issue which I think may be related

**Comment by woakesd** [comment]
PS I found a work around which is to add one space for each character in the supplementary plane.

**Comment by WojciechMula** [comment]
Sorry for the problem, will check it soon.

**Comment by pombredanne** [comment]
@woakesd Is this still an issue? I think this was fixed, but I am not 100% sure... would you be kind enough to check on the latest checkout?

**Comment by woakesd** [comment]
I think not, but I’ll need to check. 

David

📞 0131 332 7571
📱 07966 444 615
📧 ***@***.***
💻 www.woakes.net

**Comment by pombredanne** [comment]
@woakesd I am closing this for now: we have windows tests that pass alright. Please reopen if this is still an issue
