### ISSUE TITLE
Method to manually destroy automaton?

### ISSUE THREAD

**Issue by ayaanhossain** [WojciechMula/pyahocorasick#66]
Hi,

Is there a method I can call or a way to manually ensure the Automaton is destroyed? In my case I am repeatedly creating an Automaton assigned to the same variable and searching based on it, but memory seem to accumulate, which should not be the case if the previous Automaton was automatically garbage collected. Is there a way I could perhaps trigger the garbage collection?

Thanks,
Ayaan

**Comment by WojciechMula** [comment]
You should use gc module (https://docs.python.org/3/library/gc.html). Invoke gc.collect() to force garbage collection.
