### ISSUE TITLE
Releasing 1.1.5 ?

### ISSUE THREAD

**Issue by TTRh** [WojciechMula/pyahocorasick#67]
I have an encoding issue during installation (python3.6/ubuntu 16.04) while installing in 1.1.4 which is fixed by https://github.com/WojciechMula/pyahocorasick/pull/48 but not in the latest release. Any chance to have soon a release including that fix ? Thx !

**Comment by woakesd** [comment]
I would like to see a release based on the latest version.

**Comment by WojciechMula** [comment]
@woakesd Me too. I was very busy last few months, I need some time to catch up.

**Comment by WojciechMula** [comment]
@pombredanne I've just run tests on the master, and they passed. Seems OK to me.

**Comment by pombredanne** [comment]
excellent, me push this then :)

**Comment by pombredanne** [comment]
@WojciechMula done! https://pypi.python.org/pypi/pyahocorasick/1.1.5 is pushed and tagged

**Comment by pombredanne** [comment]
@TTRh Thanks a lot for this ticket.... 1.1.5 is out: closing now.

**Comment by WojciechMula** [comment]
@pombredanne Thank you very much for doing the release. :)
