### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by WojciechMula** [WojciechMula/pyahocorasick#8]
Excerpt from another e-mail from Simon Rosenthal:

> However, our requirement is to be able to locate substrings in Japanese text rather than English. When I
> loaded a set of Japanese strings, I  got this error message after the following statemnent:
> A.make_automaton()
> ... Automaton.c:automaton_make_automaton:508 - state failed!
> I'm wondering if this is any way related to UTF-8 vs Ascii ? I know Python 3 is fully UTF-8 compliant, but the
> C code may not be handling Japanese multibyte characters properly.

**Comment by Ulitochka** [comment]
Hello, and thank you for your work!
I loaded a set of Russian strings, and I got error message: A.make_automaton()
... Automaton.c:automaton_make_automaton:508 - state failed!

**Comment by WojciechMula** [comment]
Hello, thank you for the report. Could you please attach the minimal python script with Russian text? I have to reproduce the bug.

**Comment by Ulitochka** [comment]
`import ahocorasick
import random

def load_file():
    sentences_from_gzetteers = list()
    directory = '/media/sf_share/data.txt'
    input_file = open(directory, encoding='utf-8')
    for i, el in enumerate([strings for strings in [input_file.read().split('\n')][0]]):
        if i < 1000:
            sentences_from_gzetteers.append(el)
    return sentences_from_gzetteers

def create_data(data):
    data_for_automata = [sentences for sentences in sorted(set(data)) if sentences != '']
    return data_for_automata

def create_test_data(data):
    index_for_test_sentences = [random.randint(0, len(data)) for i in range(100)]
    sentences = [elements for i, elements in enumerate(data) if i in index_for_test_sentences]
    string_for_test = ' '.join(sentences)
    return sentences, string_for_test

def create_automata(data, string):
    A = ahocorasick.Automaton()
    for sentences in data:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

raw_sentences = load_file()
data = create_data(raw_sentences)
sentences, string = create_test_data(data)
create_automata(sentences, string)`

**Comment by Ulitochka** [comment]
import ahocorasick
import random

def load_file():
    sentences_from_gzetteers = list()
    directory = '/media/sf_share/ORGANIZATION_SENT.txt'
    input_file = open(directory, encoding='utf-8')
    for i, el in enumerate([strings for strings in [input_file.read().split('\n')][0]]):
        if i < 1000:
            sentences_from_gzetteers.append(el)
    return sentences_from_gzetteers

def create_data(data):
    data_for_automata = [sentences for sentences in sorted(set(data)) if sentences != '']
    return data_for_automata

def create_test_data(data):
    index_for_test_sentences = [random.randint(0, len(data)) for i in range(100)]
    sentences = [elements for i, elements in enumerate(data) if i in index_for_test_sentences]
    string_for_test = ' '.join(sentences)
    return sentences, string_for_test

def create_automata(data, string):
    A = ahocorasick.Automaton()
    for sentences in data:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

raw_sentences = load_file()
data = create_data(raw_sentences)
sentences, string = create_test_data(data)
create_automata(sentences, string)

**Comment by Ulitochka** [comment]
import ahocorasick
import random

def load_file():
    sentences_from_gzetteers = list()
    directory = '/media/sf_share/ORGANIZATION_SENT.txt'
    input_file = open(directory, encoding='utf-8')
    for i, el in enumerate([strings for strings in [input_file.read().split('\n')][0]]):
        if i < 1000:
            sentences_from_gzetteers.append(el)
    return sentences_from_gzetteers

def create_data(data):
    data_for_automata = [sentences for sentences in sorted(set(data)) if sentences != '']
    return data_for_automata

def create_test_data(data):
    index_for_test_sentences = [random.randint(0, len(data)) for i in range(100)]
    sentences = [elements for i, elements in enumerate(data) if i in index_for_test_sentences]
    string_for_test = ' '.join(sentences)
    return sentences, string_for_test

def create_automata(data, string):
    A = ahocorasick.Automaton()
    for sentences in data:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

raw_sentences = load_file()
data = create_data(raw_sentences)
sentences, string = create_test_data(data)
create_automata(sentences, string)

**Comment by Ulitochka** [comment]
def create_sutomata_rus():
    A = ahocorasick.Automaton()
    for sentences in ["!ASM Print",
                    "!ASM Print, tyre компания er",
                    "!ASM Print, рекламно-производственная компания rr",
                    "!Action Pact!",
                    "!T.O.O.H.!",
                    "!YES, лингвистический центр",
                    "!ts, магазин",
                    "!ФЕСТ",
                    '"100-th" department store',
                    '"1000 мелочей"',
                    '"1001 мелочь"',
                    '"19 отряд Федеральной противопожарной службы по Ленинградской области"',
                    '"У Друзей"',
                    '"ШТОРЫ и не только..."']:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

**Comment by Ulitochka** [comment]
def create_sutomata_rus():
    A = ahocorasick.Automaton()
    for sentences in ["!ASM Print",
                    "!ASM Print, tyre компания er",
                    "!ASM Print, рекламно-производственная компания rr",
                    "!Action Pact!",
                    "!T.O.O.H.!",
                    "!YES, лингвистический центр",
                    "!ts, магазин",
                    "!ФЕСТ",
                    '"100-th" department store',
                    '"1000 мелочей"',
                    '"1001 мелочь"',
                    '"19 отряд Федеральной противопожарной службы по Ленинградской области"',
                    '"У Друзей"',
                    '"ШТОРЫ и не только..."']:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

**Comment by Ulitochka** [comment]
test_sentences = ["!ASM Print",
                    "!ASM Print, tyre компания er",
                    "!ASM Print, рекламно-производственная компания rr",
                    "!Action Pact!",
                    "!T.O.O.H.!",
                    "!YES, лингвистический центр",
                    "!ts, магазин",
                    "!ФЕСТ",
                    '"100-th" department store',
                    '"1000 мелочей"',
                    '"1001 мелочь"',
                    '"19 отряд Федеральной противопожарной службы по Ленинградской области"',
                    '"У Друзей"',
                    '"ШТОРЫ и не только..."']

def create_sutomata_rus():
    A = ahocorasick.Automaton()
    for sentences in test_sentences[-7:]:
        for index, word in enumerate(sentences.split(' ')):
            A.add_word(word, (index, word))
    A.make_automaton()

**Comment by WojciechMula** [comment]
@Ulitochka thank you very much!
