### ISSUE TITLE
Provide manylinux wheel

### ISSUE THREAD

**Issue by sk-** [WojciechMula/pyahocorasick#91]
It would be great if `pyahocorasick` provided prebuilt wheels for linux. See https://github.com/pypa/manylinux

**Comment by pombredanne** [comment]
@sk- I am building such wheels with this build loop https://github.com/pombreda/thirdparty-manylinux/
You can try them out from here: https://dl.bintray.com/pombreda/thirdparty2/
If this works out for you and your tests work OK, we could add them to the Pypi release.

**Comment by ff4f01** [comment]
@pombredanne Thanks for providing some third party wheels.

**Comment by pombredanne** [comment]
I am adding support for the excellent cibuildwheel to get these available all the times. You can see this here. 
https://github.com/WojciechMula/pyahocorasick/actions/runs/1871630796
1.4.3 will have these pushed to PyPI
