### ISSUE TITLE
What is meant by "approximate" ... search in readme?

### ISSUE THREAD

**Issue by kootenpv** [WojciechMula/pyahocorasick#92]
> ... library for exact or approximate multi-pattern string search ...

I'm curious what is meant in the first line of the readme with "approximate"? I cannot find any functions...

**Comment by WojciechMula** [comment]
@kootenpv It means one can use wildcard during search in dictionary. So you may lookup for "?at" and get "cat", "rat", "bat", etc.

**Comment by kootenpv** [comment]
@WojciechMula Oh cool, I couldn't find anything about it. Has there been anything written on it? And does it mean that `??at` also works?

Is there a way to escape `?`?

**Comment by WojciechMula** [comment]
@kootenpv It is described in the documentation :) https://github.com/WojciechMula/pyahocorasick#automaton-dictionary-like-methods

**Comment by WojciechMula** [comment]
@kootenpv feel free to ask further question. Please reopen this issue or create new one, if required.

**Comment by kootenpv** [comment]
Thanks, it is very clear!
