### ISSUE TITLE
ImportError: No module named 'ahocorasick' （or pyahocorasick）

### ISSUE THREAD

**Issue by loveJasmine** [WojciechMula/pyahocorasick#96]
ub16hp@UB16HP:~/ub16_prj/pyahocorasick$ sudo pip3 install -e .
[sudo] password for ub16hp: 
The directory '/home/ub16hp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ub16hp/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/ub16hp/ub16_prj/pyahocorasick
Installing collected packages: pyahocorasick
  Found existing installation: pyahocorasick 1.1.10
    Uninstalling pyahocorasick-1.1.10:
      Successfully uninstalled pyahocorasick-1.1.10
  Running setup.py develop for pyahocorasick
Successfully installed pyahocorasick
ub16hp@UB16HP:~/ub16_prj/pyahocorasick$ python3 yk_test_zh.py 
Traceback (most recent call last):
  File "yk_test_zh.py", line 1, in <module>
    import ahocorasick
ImportError: No module named 'ahocorasick'
ub16hp@UB16HP:~/ub16_prj/pyahocorasick$ python3 yk_test_zh.py 
Traceback (most recent call last):
  File "yk_test_zh.py", line 1, in <module>
    import ahocorasick
ImportError: No module named 'ahocorasick'
ub16hp@UB16HP:~/ub16_prj/pyahocorasick$

**Comment by WojciechMula** [comment]
`pip3 install -e .` places a library file in the current directory. You have to tell the python interpreter to search this directory too:

```
$ export PYTHONPATH=.
$ python 3
>>> import ahocorasick
```

**Comment by WojciechMula** [comment]
BTW, if you're not going to change module's code, it will be easier just to ``pip3 install pyahocorasick``.

**Comment by loveJasmine** [comment]
no need export PYTHONPATH=.

I found root cause: pip3 work on another version python3
